SBI_CROSS_COMPILE = riscv64-unknown-linux-gnu-

CC = riscv64-unknown-elf-gcc
LD = riscv64-unknown-elf-ld
OBJCOPY = riscv64-unknown-elf-objcopy
CCFLAGS = -c -g -MMD -MP -ffreestanding -march=rv64imac_zicsr -mcmodel=medany -mabi=lp64 -fno-pie -std=gnu99
